### ISSUE TITLE
Use iOS9/10 advanced notifications

### ISSUE THREAD

**Issue by amulware** [toggl/superday#117]
The notifications support 4 buttons, we could use either the most common categories here, or just all non-commute categories.

In addition, we should consider if it is worth using the custom ui control we can use in iOS10, to show the current timeline (or just the current slot even), maybe with the last unknown entry showing a "?" inside it, which then updates as the user selects one of the options.

**Comment by amulware** [comment]
Needs design for the custom UI in the notification.

**Comment by amulware** [comment]
There is some code on `willsb-ios10-notifications` already, splitting the notification service into two for the respective platforms.

**Comment by pe0ny** [comment]
![notification - lock screen](https://cloud.githubusercontent.com/assets/5064445/20095814/b127b3ea-a5af-11e6-863d-89b3d82325a6.png) ![notification - expanded](https://cloud.githubusercontent.com/assets/5064445/20095829/c4ec9968-a5af-11e6-8454-a3d62d7c273a.png)

Display three previous time slots in the custom content area.
And four categories below: Food, Friends, Work and Leisure (we'll leave commute out since the app _should_ detect it automatically)

When user picks a category, update the custom area accordingly.

Also, please change copy to: "Howdy! What you’re doing right now?"

**Comment by sofokli1** [comment]
Do we want commute to be included as a button?
![simulator screen shot 9 nov 2016 13 06 31](https://cloud.githubusercontent.com/assets/885122/20136447/803f8c52-a67d-11e6-9824-09630fdc5ead.png)

**Comment by amulware** [comment]
Is this even possible? I was under the impression that we can only use 4 buttons.

**Comment by sofokli1** [comment]
It looks like we can use more. The screenshot is from the simulator.

**Comment by amulware** [comment]
Interesting. Let's not include it for now though. We should limit the number of options, and the app should ideally track commute automatically.
