### ISSUE TITLE
Ask feedback option

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#136]
Add feedback option so users can contact us directly from the app.

![timeline - today 1x](https://cloud.githubusercontent.com/assets/5064445/20527841/9045349e-b0d2-11e6-9417-f1b5495c70aa.png)

**Comment by amulware** [comment]
Do we have more details on what happens when the user hits that button?

In the simplest case, we can open an email-sending form, with attached log files, to the support email.
Great about that is that we then get the user's email and can answer them if we want to.

Alternatively we can have a custom dialog of some sort, which would require an endpoint from backend.

Or we could do a middle ground sort of thing: A custom form, and when the user hits 'send' it opens an email sending form with the feedback filled in (and they have to hit 'send' again).

If we have a custom form we could also include an emotion-picker like in the mobile app, asking the user if they feel :) :| or :( and asking them to rate the app if they like it.

**Comment by pe0ny** [comment]
Yes, let's keep it simple and open an email form with attached log files.
