### ISSUE TITLE
The great tracking improvement discussion of summer 2017

### ISSUE THREAD

**Issue by amulware** [toggl/superday#649]
Discuss!

**Comment by sofokli1** [comment]
In the spirit of keeping things simple the below ideas do not require backend from us, but use fabric and other third party services.

# 1. Metrics
We need a clear way to measure algo changes impact on real users. This is useful for current minor changes and for future major changes. Having a simple metric i think would make for a powerful tool in our hands. It would help in clearing uncertainties in our assumptions and give confidence in our approach, whichever that is.
Possible ways to achieve this:
  - 1. Introduce the idea of UDID just in case. No login required. Generate one if the there is none save in userDefaults and if the user reinstalls the app and gets a new UDID it’s ok for our needs.
  - 2. Have a positive and negative button for each slot that we guess. Log in an aggregated way in Fabric (like per day performance).
  - 3. Alternative to 2 could be having a footer at the end of the timeline and just ask there from 1-5 how good did we guess for the day.
  - 4. We can also imply quality of guess based on how and if the user changes our guesses.

I think that metrics would be a good idea to make our job a bit more goal oriented. So apart from the issue/milestone closed kind of approach that we have now, we would also have metrics improvement goal as well. The first is nice to have for the day to day things and the second is nice to have on the long term impact of the day to day stuff.

# 2. Passive A/B testing
I say passive just because this will not need server side to implement and use.
The idea here is that instead of rolling the changes to the app store for all users at the same time, we do a on device decision on which way to go (A or B). This will be useful for testing changes to the algo to a small percentage of the real users and measure impact with metrics (see above). Instead of looking for testers inside toggl we leverage real users that are active users of the app. Of course this approach will require more regular app store submission (sometimes just to change the A/B test). We could also take a look at apple’s new phased release but i think the first approach where we have all the control looks better to me. In general we could use this approach to test 4-5 algo changes ways at the same time with one release on the app store to different groups of people and see what worked better in a short time compared to serial testing with different app store releases.

# 3. Hotspot approach
Instead of tracking user location and when there is none we imply something different from commute is happening, we do the opposite. What i mean is use `CLLocationManager`‘s `startMonitoringVisits()` to get `CLVisit`. This will work also in the background and will simplify our logic a lot. No need for active location updates with this. We can still combine this and our current logic if needed but what i am proposing here is major changes. The idea is that we use this for getting locations that the user stays for significant time. This slots that are created based on visits can be combined with HK movement to split them into smaller slots (this is to cover the cases like us where we do a lot of stuff in the house). We should also start to use the altitude as well. We still keep the smartGuess system but change some things. The idea here is to have hotspots (visits) that keep a collections of tuples like `(category, startTime, endTime, altitude, etc)`. This way we narrow what we are going to guess on this collection next time the user visits this location. Time spent when leaving a place and going somewhere else can be called commute or use the old/current logic.
To conclude this `wip` logic, we drop the pipeline (and maybe KNN) for this simplified tracking.

# 4. Third party APIs
This can be used with our current approach or any new approach. We could use `google places API` or `foursquare API` to see for near by location based on GPS and use the POI category to map the slot created there to a specific category. So `restaurant`, `fast food` -> :superfood:, `gym` -> :superfitness:, `bar` -> :superfriends: and so on.

# 5. Taking photos
This is a crazy idea that i just want to through out there. I want the user to take picture and have them in their timeline. In a way have the + button for adding a new slot and having a second button to take a picture and add it to the timeline (design-needed) and at the same time create a new timeslot. Now from our side. In iOS 11 apple has made it very easy to use pre trained off the shelf models for image classification. We can use this without needing to know the underlying working of machine learning to identify things in photos. So we use what the classifier gives us from the image `(name, confident percentage)` and keep a dictionary of `name -> category`. So take a picture of your food -> new slot :superfood:, take a selfie in the gym -> :superfitness:, and so on.

# Conclusion
As you all can see, by using `metrics` and `A/B testing` we can test the above ideas and other ideas at the same time. I hope that at least `metrics` and `A/B testing` are welcomed by all (if not some of the other ideas as well) and implemented so that we can move forward at a faster pace. These 2 technics can be used to test even other things regarding copy in the app (like call for action copy, etc).

Feel free to talk to me about any of these.

**Comment by sofokli1** [comment]
An other point to add to `metrics` is using actionable notifications when we are not very sure about our guess. So instead of `Howdy ...` we could ask `Are you eating right now?`. Simple yes or no question. We can then turn a guess into a user input (smart guess).

**Comment by sofokli1** [comment]
Regarding more complex approaches to our problem that require the use of machine learning. The main issue with this approach is to get as much data as possible from real users to train the model. A way to overcome this problem is to write some scripts that generate pseudo data that create slots that mimic different types of lifestyle (remote workers, office workers, students, etc). We can start work with this data on the machine learning training. This generated data can also be very useful when working with the app in general to populate the UI when testing stuff (timeline, charts, animations, etc).

**Comment by Odrakir** [comment]
I completely agree on the metrics stuff. Also giving the user the opportunity to give feedback on how good the timeline is, is great. We'll have to find a way not to intrusive of doing so. It shouldn't be too hard to implement. I would first try to improve the current tracking and then see how the new version works with users.

A/B testing is something nice to have as well, thought that could take a little more planning and thinking.

About `CLVisit`, my understanding is that it has a lot of delay. But it'll be interesting to try it out and see. I think another approach can be monitoring regions, I'm going to try it as significant location changes are not working very well for me.

Not sure how third party APIs will fit with Superday and smart guesses... but... maybe?

And about the crazy idea... yeah, it's crazy for now :)

**Comment by Odrakir** [comment]
This is my research so far, I am building a test app to see if any of this makes sense:

### Location last

The way the algorithm works right now I think we are giving too much importance to location changes, for the little of them we actually get. In my opinion we should be able to build a timeline without location changes and use them only to help with smart guesses or to infer commutes when no other data is available. I'm writing code for that, we'll see... But the general idea is that we first build a timeline without location and then we use location to see when did the user move.

### CoreMotion vs HealthKit

I've been testing CoreMotion and I think we should really consider switching. Once you filter the data you get very accurate results and it even detects movement in a vehicle and tags it so, even if underground. Also it's much less intrusive for the user, the authorization is just like the notifications one. We'll get that and all of what HK gives us (except sleep, which could be smart guessed anyway).

The only problem is that as far as I know it can't be queried in background, so we have to do it when the user starts the app, and it'll only store up to 7 days of data. So if the user opens the app less frequently we will loose some of the data. If we can live with that (the app is supposed to be used more frequently) I think it's the way to go.

### Region monitorin vs Significant Location Changes

I don't know about the rest, but I'm not really happy with SLC accuracy. I'm trying a solution based on region monitoring, I'll test tomorrow, I'll let you know how that works. Basically I'm setting a region where the user starts the app, and when he moves I move the region to where ever he is, and I keep updating it.

### Smarter Smart Guesses

This was mentioned above, but I think we should add more data to smart guesses and also increment their live (right now it's just a month) and also compare slots for the same time in different days of the week, even if we assign them less weight.

### App architecture

Finally (I'm sure you all heard me say this many times) I think we have a problem with the architecture, and part of the problem is there, because it's getting unwieldy. Not all logic should be in Services, Services shouldn't reference each other and we are missing where to put the business logic (which shouldn't ever be in view models either). Some of it is about naming, ok, but some isn't. Services should take care of the low level stuff. For example: the `LocationService` should be the only place in the app where we import `CoreLocation`, and then there's this *business logic* part where we tied all up together. Finally the view model takes that data and just transforms it for the view to read.

I'll be happy to show you with the test app I'm building.

**Comment by sofokli1** [comment]
Location last
CoreMotion vs HealthKit
Region monitorin vs Significant Location Changes
I dont have any issue with improving any of the above as long as we decide that the 7 days data (core motion) is not a big issue. For the rest, if it's better then what we have then no issue as well.

Smarter Smart Guesses
I agree that the 1 month is too short of a time period for the amount of user input that we get. We should also see for ways to convert `guess` to `user input` if it's good guess (somehow). maybe return a `certainty score` together with the `smartGuess` and based on a certain threshold (to be decided) convert that guess into a `smartGuess`, but also have option to downgrade it if the user edits it (same goes for user input that is changed by the user later on to something else).

App architecture
In general i agree but on a case to case bases.

**Comment by sofokli1** [comment]
in general improvements on what we have will always be good and welcome but i think what we need to focus more is how get new categories even when the user is not saying anything (you know, make the app really creepy 😛 ). I think this i the hard part, because improving on what we already have and works is relatively easy.

**Comment by sofokli1** [comment]
Some other thoughts regarding HK regardless if we are going to keep it for commute detection or not. We can use the health data that are added from third party fitness apps. people that go for a run may use `run keeper` so we should use that data (and other well known fitness apps data) to guess fitness categories with very high accuracy (in a way we could count those the same as user input data).

also take a look at dieting apps that people use to keep track of their meals and when they eat them, it can help with food categories.

**Comment by Odrakir** [comment]
This is how this app handles when the user doesn't come back for a week.

It can be done better.

![fullsizerender 2](https://user-images.githubusercontent.com/724743/27819499-dbf57fb6-609a-11e7-857e-2b0cb863c868.jpg)

**Comment by amulware** [comment]
Here are some comments, more or less in order as things are mentioned above. Just my thoughts in the moment, nothing here is final.


## Metrics

Yes, it would be good to have more/better metrics. Agreed. We'll have to see how we can get the most bang for our buck here though.

I'm not convinced if it is a good idea to have users 'rate' a timeline. But getting upvotes/downvotes/stars for different algorithms is a pretty straight forward way of getting feedback at least. Probably makes more sense to do this for the whole timeline as one, not per timeslot - less invasive, and much easier to evaluate for us as well.

Of course, note that we already track how often users edit slots. We could see how much we can do with that data, or what exactly we would need to track more to make it usable.

Lastly, while I agree with tracking, there of course remains the question whether we have enough users for meaningful A/B testing.


## A/B testing

In principle I have no issues with this, and I agree that we can use app-internal feature flags or something to implement this easily enough.

The main problem is really the number of users. Even Toggl's A/B tests with (tens of) thousands of users often have statistically insignificant results.

If a change is so significantly better that you would notice from dozens of users, shouldn't we be able to notice it ourselves?


## HotSpot approach

I'm not at all convinced about by CLVisit and associated APIs. But a lot of this might depend exactly how we want to show data semantically (whether or not the timeline is gonna change and show different/more data).


## Third party APIs

Might be tricky for a variety of reasons (not all technically), but I'm up for trying this. I'm not sure it would be very accurate though (mostly because we don't necessarily have accurate locations, and because there usually are a lot of different places close to each other).


## Photos

A bit crazy, yeah. Don't see this happening, but who knows. (That being said, some apps access photo metadata to get access to location/time thingies, I believe... maybe.. some day.. probably not.)


## Better notifications

Yes, we should have these. The problem being that we then have to generate a TTL, see if we can make sense of the last slot, and if not, send a notification maybe, but do we persist the TTL at that point? Probably not, but maybe we would get data in just a few minutes that would help us make sense of it... Not to mention, HK isn't getting us live data most of the time. :/


## Machine learning

In the long term, we probably need this. But as you say, we need MUCH data for that. It's a bit of a chicken and egg thing.

Generating timelines is an interesting idea, but it will be hard to account for all the weird things people do, and the inaccuracy of our data sources, etc. etc.


## Location last

I disagree that we give location changes too much importance. With HK disabled they still give pretty decent updates for larger movements - at least for some people.

I'm open to proposals for generating timelines without locations, and just using locations for guessing and stuff. But we have to take into account users who don't allow us some of the data sources, or who just don't have data there, for whatever reason.


## CoreMotion vs HealthKit

CoreMotion sounds interesting, but a lot of it seems to overlap with what HK already gives us, and of coruse some things are missing.

Questions: How do we get CM data? Only for 7 days, but do we get it in the background? CAN we get it in the background? If the phone is locked? If so, we could use it for more-real-time data gathering, compared to HK, to get data, maybe at least whern woken by location changes.


## Region monitoring vs SLC

We tried region monitoring (always have a region on the current location with minimum radius and detect when user leaves that - rinse and repeat), but as far as I remember (maybe @willsb remembers more details) it really didn't work very well. I think this is because in the end, they both use the same information under the hood, and telling SLC to give us updates if we moved more than 100 meters, is basically the same as setting up a 100m region ourselves, except SLC is easier to use.


## Smarter Smart Guesses

Yes please. More ideas here are VERY welcome. I think our timeline isn't that bad these days. If we could nail the guessing, that would improve the app a lot.


## App architecture

You had weeks to refactor! :P

I have no issues with how I understand your alternative architecture. We'll just have to see when/how we can do it best, while also keeping other things moving. Proposals welcome.


## Last words

I very much agree with the sentiment to make the app creepier. We should see what we can do with the data we already have, and what data we can add to give us more context. This needs much thinking and figuring out.

**Comment by amulware** [comment]
Another idea by @Odrakir that we have to be careful with, but that could improve our guessing a lot at the start: location-less, time based default smart guesses (for most comment working/food/whatever times). If accurate, these would help create good timelines right from the start, and if inaccurate, at least the user hopefully corrects them, so they will be 'killed off', and replaced by better ones.

This would require us to change smart guesses to work without location and time based - which might be good in general though. There is probably other edge cases as well, but it sounds promising.

**Comment by Odrakir** [comment]
I think we should start splitting this into different issues and discuss the relevant ones separately.

**Comment by amulware** [comment]
Closing this as we have moved on from this.
