### ISSUE TITLE
Feedback form can miss Cancel and Send buttons

### ISSUE THREAD

**Issue by amulware** [toggl/superday#682]
Possibly only the first time it is used after installing the app.

If this cannot be fixed, maybe it is time we look into a custom solution.

**Comment by pe0ny** [comment]
Interesting because i reinstalled the app this morning and buttons were on their place...

**Comment by amulware** [comment]
I don't want to reinstall right now, but at least I saw this behaviour just now. (and now not anymore)

Something to investigate.

**Comment by Odrakir** [comment]
Yes, I saw it too.

**Comment by sofokli1** [comment]
i saw it too but the button is there and touchable. I just think the text is white. it might be related to this [line](https://github.com/toggl/superday/blob/develop/teferi/AppDelegate.swift#L166) and based on [docs](https://developer.apple.com/documentation/uikit/uinavigationbar/1624937-tintcolor) i think we should be using `barTintColor` instead of `tintColor`. what do you think @Odrakir

**Comment by Odrakir** [comment]
You are probably right, the strange thing is that this only happens sometimes... 🤷‍♂️
