### ISSUE TITLE
Average time slot editing per day per user

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#699]
At the moment we can get a number of time slots edited per day per user but we would like to know out of how many so we can get the percentage.

**Comment by sofokli1** [comment]
The idea here was to send these data to fabric when app goes to background so we know how many changes have been made etc. The issue is that all events in fabric do not have the option to set a date for when the event happened. It is more like a `log something at the moment that it happens` kind of a system. So when logging data for the last week all at ones it seems like it all happened at the same day. I thought to put the date as an attribute but only string and numbers can be added as attributes. i tried to put the date as a string but there is no way to filter and group based on the attribute. Any idea on how to deal with this is welcome. There also is the question, if we don't mind being precise about the date but be ok with the general trend in the data.

**Comment by amulware** [comment]
We could send a fabric event for every single time entry created (i.e. when the user opens the app and it fills three days of timeline, send 30 events).

Then we can easily compare that number to the edits made.

This might also allow us to use the data for other purposes (include the category, whether it has a location/smart guess, etc as attributes).

On the other hand, it is a lot of data, and it still does not allow us to get a day-to-day comparison, of total time entries vs those edited. However, this approach also does not run into the issue that users can edit stuff on a day after we send that they didn't edit.

**Comment by amulware** [comment]
We could even go as far as to send more data on the edits as well (did the edited time entry have a category, a smart guess, a location, ...)
