### ISSUE TITLE
Changing mid-night logic to take into account real sleep time

### ISSUE THREAD

**Issue by amulware** [toggl/superday#704]
The idea being to start the day when the user goes to sleep, not at midnight.

Apart from significant technical challenges, there are logical ones as well. Issues that have to be dealt with include:

- how to handle if a user has no sleep slot for a day? two days? two weeks?
- how to handle if a user has only small sleep slots spread across the day/night?
- how to handle that days can have basically arbitrary lengths? how will this work in statistics?
- how to handle a user whose week is into 6 waking/sleeping periods? does the week have 6 days? do they have fewer weeks/days that year?

And I'm sure there are other problems with this.

**Comment by Odrakir** [comment]
I say those are a lot of problems. Now I understand Heidi's concerns, but for me they are not bad enough to get into this mess. 

A day is a day: a 24 hour period staring at 12:00 and we count how many hours you slept in that period. 

The thing would be totally different if we were making a sleep tracker in which, then yes, I would like to know the amount of time I slept "last night" where last night is the amount of time since I went to bed yesterday till I woke up today.

**Comment by amulware** [comment]
While I'd like this, I don't see it being done anytime soon.
