### ISSUE TITLE
Figure out if CLVisits or region monitoring gives better/more location updates than SLC

### ISSUE THREAD

**Issue by amulware** [toggl/superday#728]
I believe the prototype is already recording/logging these, so it should be easy to look over the logs (of at least three people) and do a bit of regex/spreadsheet magic to make some estimations.

We only need to get the log out of the app and make sure that everything is in fact logged correctly.

Let me know once this is easily possible and how, since I'd like to look at this as well. Please post data of statistical nature and conclusions below (don't post real locations, for hopefully obvious reasons).

**Comment by Odrakir** [comment]
The prototype is recording all three for everybody (sorry for your battery :P). The filtering should be improved (it's returning too many results even with low accuracy). And I think it's not working properly for visits.

Anyway, you can't see any of this because I didn't include any mechanism to see the log. I'll add that and fix CLVisits.

**Comment by Odrakir** [comment]
Repeated here: #306
