### ISSUE TITLE
Migrate old TimeSlot data to new DB structure

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#977]
Find the best way to keep old data (at least for the last week)

**Comment by sofokli1** [comment]
I get that this is needed for existing users, but I think this makes sense to be implemented after the new way for persistency is all done and ready to be used (as in usable by a new user).

**Comment by sofokli1** [comment]
@Odrakir what are your thoughts on this ☝️?

**Comment by Odrakir** [comment]
I think we should at least make a description of what it will imply and add it here.

**Comment by sofokli1** [comment]
Based on the new architecture we need to split `old TimeSlot` into the new components that are needed for the `new Timeslots`. I would say that we can achieve this with an Interactor/script that tries to split the `old TImeslots` into `TimeSlotPM`, `LocationEventPM` and `MotionEventPM`.

- `TimeSlotPM` can be easily mapped from the `old Timeslots` since all the needed properties are available immediately
- `LocationEventPM`: here we are missing 2 values `altitude` and `accuracy`. For the purpose of the migration I would say that we could use some default values for these (values should be choses so that they do not weigh more than new location data when the new algo is ready).
- `MotionEventPM` we can get the `startTime` and `motionType` from the `old TimeSlot` but only one motionEvent per slot.

**Comment by Odrakir** [comment]
I think for `LocationEventPM` we should use the logs instead. Every location is being logged, we just have to filter them a little and save them in the DB.

And for `MotionEventPM` we should do as you say, except for the last week, were we should get every event there is.

**Comment by sofokli1** [comment]
location part is covered in issue #979 and implemented in PR #1034
